language: node_js
node_js:
  - "6.16.0"
before_install:
  - npm install -g codecov
after_success:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
